<div class="footer-spacer"><img src="<?php echo $basedir;?>/img/spacer.gif"/></div>
<footer id="footer">
    <div class="container-fluid">
        <div class="row">
            
            <div class="col-xs-12 hidden-md hidden-lg hidden-sm">
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-3681218186493233"
                     data-ad-slot="2551328309"
                     data-ad-format="auto"></ins>
                <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
            
            <div class="col-md-4 hidden-xs">
                <div class="fb-like" data-href="https://www.facebook.com/KiedyMsza" data-width="100%" data-layout="standard" data-action="like" data-show-faces="true" data-share="true" data-colorscheme="dark" data-connections="20"></div>
            </div>
           
            <div class="col-md-4 hidden-xs">
                <gcse:search enableAutoComplete="true" linkTarget="_self" enableOrderBy="false"></gcse:search>
            </div>
            
            <div class="col-md-4 hidden-xs footer-menu">
                <ul>
                    <li><a href="<?php echo $basedir;?>/o-projekcie/#wsparcie">Wsparcie</a> &nbsp; </li>
                    
                </ul>
            </div>
        </div>
    </div>
</footer>

