<div class="footer-spacer"><img src="<?php echo $basedir;?>/img/spacer.gif"/></div>
<footer id="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="fb-like" data-href="https://www.facebook.com/KiedyMsza" data-width="100%" data-layout="standard" data-action="like" data-show-faces="true" data-share="true" data-colorscheme="dark" data-connections="20"></div>
            </div>
           
            <div class="col-md-4 hidden-xs">
                <gcse:search enableAutoComplete="true" linkTarget="_self" enableOrderBy="false"></gcse:search>
            </div>
            
            <div class="col-md-4 col-xs-8 footer-menu">
                <ul>
                    <li><a href="<?php echo $basedir;?>/konkurs">Konkurs - Wakacyjne zdjęcie kościoła</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

