    <meta charset="utf-8">
    <title><?php echo $title;?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="<?php echo $description;?>" />	
    <meta name="keywords" content="<?php echo $keywords;?>" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="<?php echo $title;?>" />
    <meta property="og:description" content="<?php echo $description;?>" />
    <meta property="og:image" content="<?php echo $image;?>" />
    <meta name="google-site-verification" content="-D0vYmVgnDtABQXkRlvnvvvsjGbkjkNTWMQ6zkFc1oI" />
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    
    <link rel="stylesheet" href="<?php echo $basedir;?>/js/pickadate.js/lib/compressed/themes/default.css" id="theme_base">
    <link rel="stylesheet" href="<?php echo $basedir;?>/js/pickadate.js/lib/compressed/themes/default.date.css" id="theme_date">    
      
      
    <!-- fonts -->
    <link href='//fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <!-- /fonts -->
    
    <link rel="stylesheet" href="<?php echo $basedir;?>/css/kiedymsza.css">
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?libraries=places,visualization&v=3.exp&sensor=true&key=AIzaSyCuhS49N8-uoDHTr6juegvG-xhi5DXFXks"></script>

    <script type="text/javascript">
        var REST='<?php echo $basedir;?>/rest';
        var BASEDIR='<?php echo $basedir;?>';
    </script>
    
    <script src="<?php echo $basedir;?>/js/fileupload/jquery.knob.js"></script>

    <!-- jQuery File Upload Dependencies -->
    <script src="<?php echo $basedir;?>/js/fileupload/jquery.ui.widget.js"></script>
    <script src="<?php echo $basedir;?>/js/fileupload/jquery.iframe-transport.js"></script>
    <script src="<?php echo $basedir;?>/js/fileupload/jquery.fileupload.js"></script>
    
    <!-- Our main JS file -->
    <script src="<?php echo $basedir;?>/js/fileupload/script.js"></script>    
    
    <link rel="stylesheet" href="<?php echo $basedir;?>/css/jquery.fancybox.css" type="text/css" media="screen" />
    <script type="text/javascript" src="<?php echo $basedir;?>/js/jquery.fancybox.js"></script>    
    
    <script type="text/javascript" src="<?php echo $basedir;?>/js/main.js"></script>
    
    
    
    <link rel="shortcut icon" href="<?php echo $basedir;?>/img/favicon.png">
