    <meta charset="utf-8">
    <title><?php echo $title;?></title>
    <meta name="description" content="<?php echo $description;?>" />	
    <meta name="keywords" content="<?php echo $keywords;?>" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="<?php echo $title;?>" />
    <meta property="og:description" content="<?php echo $description;?>" />
    <meta property="og:image" content="<?php echo $image;?>" />
    <meta property="og:url" content="<?php echo $title;?>" />
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    
    <link rel="stylesheet" href="<?php echo $basedir;?>/js/pickadate.js/lib/themes/default.css" id="theme_base">
    <link rel="stylesheet" href="<?php echo $basedir;?>/js/pickadate.js/lib/themes/default.date.css" id="theme_date">    
      
      
    <!-- fonts -->
    <link href='//fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
    <!-- /fonts -->
    
    <link rel="stylesheet" href="<?php echo $basedir;?>/css/kiedymsza.css">
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?libraries=places&v=3.exp"></script>

    <script type="text/javascript">
        var REST='<?php echo $basedir;?>/rest';
    </script>
    
    <script src="<?php echo $basedir;?>/js/fileupload/jquery.knob.js"></script>

    <!-- jQuery File Upload Dependencies -->
    <script src="<?php echo $basedir;?>/js/fileupload/jquery.ui.widget.js"></script>
    <script src="<?php echo $basedir;?>/js/fileupload/jquery.iframe-transport.js"></script>
    <script src="<?php echo $basedir;?>/js/fileupload/jquery.fileupload.js"></script>
    
    <!-- Our main JS file -->
    <script src="<?php echo $basedir;?>/js/fileupload/script.js"></script>    
    
    <script type="text/javascript" src="<?php echo $basedir;?>/js/main.js"></script>