<a href="https://goo.gl/hJTMzB" target="_blank" alt="wsparcie 2zł"><img width="15%" src="<?php echo $basedir;?>/img/2zl.png"/></a>
<a href="https://goo.gl/Pv34ap" target="_blank" alt="wsparcie 5zł"><img width="15%" src="<?php echo $basedir;?>/img/5zl.png"/></a>
<a href="https://goo.gl/m7LwyM" target="_blank" alt="wsparcie 20zł"><img width="35%" src="<?php echo $basedir;?>/img/20zl.jpg" style="margin-left: 10px;"/></a>
		