<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.9&appId=955693664451085";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MS4VGL"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MS4VGL');</script>
<!-- End Google Tag Manager -->


<nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
   
                <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                          <span class="sr-only">Menu</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $basedir;?>">KiedyMsza.pl</a>
                
                </div>
  
                <div id="navbar" class="collapse navbar-collapse">
      
                        <ul class="nav navbar-nav navbar-right">
                          <li>
                            <a href="<?php echo $basedir;?>/o-projekcie/">O projekcie</a>
                          </li>
                          <li>
                            <a href="<?php echo $basedir;?>/login/" class="a_login">Login</a>
                          </li>
                          <li>
                            <a href="<?php echo $basedir;?>/mapa/">Mapa</a>
                          </li>
                          <?php if (isset($moremenu) && is_array($moremenu)) foreach($moremenu AS $a): ?>
                          <li>
                            <?php echo $a;?>
                          </li>
                          <?php endforeach; ?>
                           <?php if (!isset($moremenu)): ?>
                          <li class="hidden-lg hidden-md">
                            <a href="<?php echo $basedir;?>/mapa?route">Szukaj mszy św. w trasie</a>
                          </li>
                          <?php endif; ?>
                        </ul>
                </div>
        </div>
</nav>
  
  <?php
  
    //die('</div><center style="margin-top:100px">Przerwa tchniczna, ok 30 min.</center></body></html>');
