  <nav class="navbar navbar-default" role="navigation">
    
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <a class="navbar-brand logo" href="<?php echo $basedir;?>">KiedyMsza.PL</a>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="<?php echo $basedir;?>/o-projekcie/">O projekcie</a>
        </li>
        <li>
          <a href="<?php echo $basedir;?>/login/" class="a_login">Login</a>
        </li>
        <li>
          <a href="<?php echo $basedir;?>/mapa/">Mapa</a>
        </li>
      </ul>
    </div>
  </nav>