<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.3&appId=955693664451085";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  <nav class="navbar navbar-default" role="navigation">
    
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <a class="navbar-brand logo" href="<?php echo $basedir;?>">KiedyMsza.PL</a>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="<?php echo $basedir;?>/o-projekcie/">O projekcie</a>
        </li>
        <li>
          <a href="<?php echo $basedir;?>/login/" class="a_login">Login</a>
        </li>
        <li>
          <a href="<?php echo $basedir;?>/mapa/">Mapa</a>
        </li>
        <?php if (isset($moremenu) && is_array($moremenu)) foreach($moremenu AS $a): ?>
        <li>
          <?php echo $a;?>
        </li>
        <?php endforeach; ?>
        
        
      </ul>
    </div>
  </nav>